import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/component/navbar/page";
import { ContextProvider } from "@/context/CartContext";

export const metadata: Metadata = {
  title: "Next Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>
          {/* <Navbar /> */}
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
