import { Metadata } from "next";
import "./store.css";
import Product from "@/component/products/product";
import "server-only";
import Navbar from "@/component/navbar/page";

export const metadata: Metadata = {
  title: "Store",
  description: "Generated by create next app",
};

const Store = () => {
  return (
    <div>
      <Navbar />
      <div className="store-page">
        <div className="productWrapper">
          <Product />
        </div>
      </div>
    </div>
  );
};

export default Store;
